FROM python:3.9-alpine

ENV PATH="/bluestack:${PATH}"

COPY ./requirements.txt /requirements.txt
RUN apk add --update --no-cache --virtual .tmp gcc libc-dev linux-headers
RUN pip install -r /requirements.txt

RUN mkdir /bluestack
COPY ./bluestack /bluestack
WORKDIR /bluestack

RUN adduser -D user
USER user