# Generated by Django 3.2 on 2021-04-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Read'), (2, 'Write'), (3, 'Delete')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('access_type', models.ManyToManyField(to='user.AccessType', verbose_name='List of Access')),
                ('resource_permission', models.ManyToManyField(to='user.Resources', verbose_name='List of Resources')),
            ],
        ),
    ]
