# Generated by Django 3.2 on 2021-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role_type',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role_type',
            field=models.ManyToManyField(to='user.Roles'),
        ),
    ]
